vich_uploader:
    db_driver: orm

    mappings:
        tp_images:
            uri_prefix: '%tp_images%'
            upload_destination: '%kernel.project_dir%/public%tp_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
