<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUlacOGs\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUlacOGs/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerUlacOGs.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerUlacOGs\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerUlacOGs\App_KernelProdContainer([
    'container.build_hash' => 'UlacOGs',
    'container.build_id' => 'c7271131',
    'container.build_time' => 1629816949,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUlacOGs');
