<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCyIWQla\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCyIWQla/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCyIWQla.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCyIWQla\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCyIWQla\App_KernelDevDebugContainer([
    'container.build_hash' => 'CyIWQla',
    'container.build_id' => 'f2bae2d1',
    'container.build_time' => 1630225296,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCyIWQla');
