<?php

namespace ContainerUlacOGs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBabyControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\BabyController' shared autowired service.
     *
     * @return \App\Controller\BabyController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BabyController'] = $instance = new \App\Controller\BabyController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\BabyController', $container));

        return $instance;
    }
}
