<?php

namespace ContainerUlacOGs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoyRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\BoyRepository' shared autowired service.
     *
     * @return \App\Repository\BoyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\BoyRepository'] = new \App\Repository\BoyRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
