<?php

namespace ContainerUlacOGs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchToyService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SearchToy' shared autowired service.
     *
     * @return \App\Form\SearchToy
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SearchToy'] = new \App\Form\SearchToy();
    }
}
