<?php

namespace ContainerUlacOGs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchBabyService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SearchBaby' shared autowired service.
     *
     * @return \App\Form\SearchBaby
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SearchBaby'] = new \App\Form\SearchBaby();
    }
}
